### ISSUE TITLE
Drive train code 

### ISSUE THREAD

**Issue by TytanRock** [De-La-Salle-Robotics/Robot-2019#1]
We need to develop drive train code to go onto the test chassis that we have

**Comment by Pharmyy** [comment]
First check at drive train code implemented here:
https://github.com/De-La-Salle-Robotics/Robot-2019/commit/17a99b3ea4b16b7d89f8a5544c188f3d8af2ad20

**Comment by TytanRock** [comment]
https://github.com/De-La-Salle-Robotics/Robot-2019/pull/2 fixes this
