### ISSUE TITLE
Arm Code

### ISSUE THREAD

**Issue by TytanRock** [De-La-Salle-Robotics/Robot-2019#3]
We have decided to use an arm for our hatch panel manipulator, so we need to develop the code for it.

We know it will use a hard-stop for the down position, we should add a limit switch and ensure we don't drive the arm further down when it's already down.

Criteria for this:
 - [x] Hardware on the robot
 - [x] Code to actuate the arm up and down
 - [x] Implemented limit switch to ensure motor does not drive when the arm is down
 - [x] Implemented limit switch to ensure motor does not drive when arm is up
 - [x] Code tested on robot

Check these boxes as they are completed. Code for this will be done on the [arm branch](https://github.com/De-La-Salle-Robotics/Robot-2019/tree/Arm-Branch)

If any of these criteria are not possible, comment below with the reason why

**Comment by Pharmyy** [comment]
We have Limit switches done on a counter, the arm lift coding done from following wpi screensteps, and an OI set up so that the arm can be programmed to certain buttons currently as when held the arm raises. Tomorrow you will have to check everything and make sure that it is done right. I have not saved anything or made changes to any of the previous code and have the code I wrote today each in separate files.

**Comment by TytanRock** [comment]
@PUNKING7762 Feel free to commit the changes to the arm branch, that's the
point of git. Whatever you do can be undone, so you can't destroy the whole
project. And I can review it tonight and see how it looks

**Comment by Pharmyy** [comment]
How do we switch branches to commit the arm on Tortoise

**Comment by TytanRock** [comment]
Right click, tortoisegit, show log. Then right click on working tree and
fetch from origin. There will be an orange thing with origin/armbrach right
click on that and switch/checkout to it

**Comment by Pharmyy** [comment]
So we committed everything on Tuesday and now some of the code on vs says deleted from disk but the code is still there does that mean anything?

**Comment by TytanRock** [comment]
Deleted from disk? Can you take a screenshot of the message and post it?
Use print scrn, then ctrl-v inside the comment box and it'll paste the
image

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/51707462-495d3200-1fef-11e9-832f-7146f620c07e.png)

**Comment by TytanRock** [comment]
You lost the vendordeps folder. Right click on build.gradle and manage
vedor libraries to add it back in

**Comment by Pharmyy** [comment]
What option 
![image](https://user-images.githubusercontent.com/46694778/51708475-02247080-1ff2-11e9-82af-87a21aa37329.png)

**Comment by TytanRock** [comment]
Install new library (offline) it's documented in the ctre documentation I
showed you

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/51709000-4ebc7b80-1ff3-11e9-9057-8e5efb003faa.png)
It didn't work

**Comment by TytanRock** [comment]
Oh, I see what's going on. The code is in the window but it got deleted
from the project. If you switch/checkout back to master you should have all
the code again. When I get there today I'll go over what happened with the
arm commit, I think I know what happened but want to make sure everything
matches with what you did.

**Comment by Pharmyy** [comment]
Ok so I tried tp switch/ checkout back to master on tortoise git but nothing showed up. Am I doing something wrong?

**Comment by TytanRock** [comment]
Is it a successful checkout? Screenshot the show log window

**Comment by Pharmyy** [comment]
We can't even get there I tried to do it like I would normally commit

**Comment by TytanRock** [comment]
You can't right click, tortoisegit, show log?

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/51711075-056f2a80-1ff9-11e9-8a48-7d29e762027d.png)
Nope

**Comment by TytanRock** [comment]
You need to right click in the project folder, not the desktop. It's under
documents/7762

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/51711453-2dab5900-1ffa-11e9-830f-e7837557de23.png)
Yes or no

**Comment by TytanRock** [comment]
Close visual studio code and click yes

**Comment by Pharmyy** [comment]
It should be done

**Comment by TytanRock** [comment]
Can you build the code now?

**Comment by Pharmyy** [comment]
Yes

**Comment by TytanRock** [comment]
Good, I'll be on my way in a bit so I can review that arm code with you

**Comment by Pharmyy** [comment]
Ok so we have the deleted from disk problem again. I tried adding the vendordeps files back in and it says no new files and I also tried switching/ checking out back to master and everything is up to date what should I try next?
![image](https://user-images.githubusercontent.com/46694778/52056939-ad24b500-2531-11e9-8159-28f05586849a.png)

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52057500-2b358b80-2533-11e9-8beb-e7d992047859.png)
Does this look good for the servo motor for the hatch panels?

**Comment by TytanRock** [comment]
So the claw will be controlled via pwm servos. That means you need to use
wpi's servo class which you should find online. And to solve the deleted
from disk problem you need to close all tabs from vscode, make sure you
checked out latest on arm branch, and then open the right file again.

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52059375-b3b62b00-2537-11e9-8528-10bc88a2fe3a.png)
Is this good?

**Comment by TytanRock** [comment]
Sorta, try building it. I doubt it'll build. Did you read the documentation
for wpi's servo class?

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52059531-114a7780-2538-11e9-8292-f231dc3094eb.png)

**Comment by TytanRock** [comment]
Ctrl click the word servo and send a screenshot of what comes up

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52059652-638b9880-2538-11e9-9fb2-15229a43e14a.png)

**Comment by TytanRock** [comment]
That shouldn't be building. I don't know how it's saying build successful.
Look at this:
http://first.wpi.edu/FRC/roborio/beta/docs/java/edu/wpi/first/wpilibj/Servo.html

Use setangle, and set it to be min angle/max angle when a button is pushed,
otherwise do nothing

**Comment by Pharmyy** [comment]
So rewrite the code completely?

**Comment by TytanRock** [comment]
No, only the claw set. The logic is the same either way, you just need to
replace the motor controller set with a pwm set

**Comment by Pharmyy** [comment]
So this is what I currently have but when you say set the angle to a button is that done the same way the joystick was?
![image](https://user-images.githubusercontent.com/46694778/52062185-04308700-253e-11e9-8626-807061e65a52.png)

**Comment by TytanRock** [comment]
The documentation I showed was detailing how the pwm class operates. I
wanted you to call claw.setAngle with either min angle or max angle passed
as a parameter.

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52064990-ac951a00-2543-11e9-8463-cac13e52d514.png)
Ok here is were I am at I am having a really hard understanding what you mean

**Comment by TytanRock** [comment]
Arm will have two servo references, similar to how it has one Victorspx
reference. Make sure you add them to the constructors, and set them in the
constructor.

Arm will also have a method called processClaw or something like that (make
it match what the other methods are like). It will take two parameters,
claw open and claw close. The logic will go something like this:

''' java
If(clawClose)
{
   Servo1.setAngle(kAngleMax);
   Servo2.setAngle(kAngleMax);
}
Else if(clawOpen)
{
   Servo1.setAngle(kAngleMin);
   Servo2.setAngle(kAngleMin);
}
'''

Make sense?

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52067569-dac92880-2548-11e9-9eb8-2068bc700548.png)
Yes me and Cody can't figure out why this error is here?

**Comment by TytanRock** [comment]
What does it say when you hover over it?

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52068507-ca19b200-254a-11e9-8300-5f3dc6503bab.png)

**Comment by TytanRock** [comment]
You are missing a curly brace delete the `public void setAngle(double degrees){ ` line

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52071726-91c9a200-2551-11e9-9fe3-b9246dd41cf1.png)
this happened

**Comment by TytanRock** [comment]
Count open and closed curly braces and make sure they are equal. You're
missing closed curly braces

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52074164-44e8ca00-2557-11e9-9656-b0a8bb4bbf9e.png)
![image](https://user-images.githubusercontent.com/46694778/52074177-4dd99b80-2557-11e9-8ab8-2152694c857e.png)
Ok we have checked all the curly braces and then all of a sudden this happened

**Comment by TytanRock** [comment]
You're importing pwm and defining it in the same file. Rename your pwm
class to something else. Then the kMin and kMax values should be defined
inside the file, so final Int kMin = 0; or something like that

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52075227-c6415c00-2559-11e9-8994-915c4d1202d2.png)
![image](https://user-images.githubusercontent.com/46694778/52075251-d35e4b00-2559-11e9-9c2c-bd5fcfe2bfa1.png)
![image](https://user-images.githubusercontent.com/46694778/52075265-dc4f1c80-2559-11e9-8b63-92be1b4f0118.png)
Ok so I tried naming it something else but it didn't work then there is these two issues

**Comment by TytanRock** [comment]
Servo1 and servo2 aren't defined in the class. You have a single servo
reference (pwmServo) you need to rename the variable to servo1 and add a
servo2.

The final Int goes in the same area as servo1 and servo2, outside the
method.

**Comment by TytanRock** [comment]
Also Int should not be capitalized, I'm writing this on my phone so I get
random caps

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52077081-191d1280-255e-11e9-8858-bea81f86edfb.png)
I kind of understand what you mean but at the same time I don't.

**Comment by TytanRock** [comment]
That curly brace with the red squiggle under it needs to be deleted.

This.servo1 instead of this.servo, same for servo2

Add another servo parameter inside the constructor

And directly under the Servo servo2 line, add the final int variables

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52077641-7c5b7480-255f-11e9-90c1-62bfac39c6fa.png)
This still hasn't gone away

**Comment by TytanRock** [comment]
Ah, I didn't see that it was outside the arm class. Take all the code and
move it to a new file called PWM1.java. Java classes need their own file

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52078046-42d73900-2560-11e9-94ab-eb85135d1565.png)
Ok how do I fix this

**Comment by TytanRock** [comment]
The final int stuff at the top of the file should resolve that

**Comment by TytanRock** [comment]
Oh, you have the final ints inside the constructor. Move it out of the
constructor

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52078258-bed18100-2560-11e9-8bb3-6aabff812efd.png)

**Comment by TytanRock** [comment]
Much better. Now your constructor still doesn't have two parameters. You
made another method, the private void one, and that has the right parameter
arguments for your constructor. Delete the private void and move the
parameters to the constructor

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52079903-99467680-2564-11e9-8444-04b911f0abcb.png)
![image](https://user-images.githubusercontent.com/46694778/52079933-a7949280-2564-11e9-8b0c-725f01bf32f1.png)
![image](https://user-images.githubusercontent.com/46694778/52079946-af543700-2564-11e9-97a5-bd411b7df0d2.png)
What am I doing wrong?

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52080341-84b6ae00-2565-11e9-8c88-e5e0b338cdd0.png)This is where I got to

**Comment by TytanRock** [comment]
Public PWM1(parameters)

Parameters should be *Servo servo1, Servo servo2*

Remove the parenthesis stuff at the end

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52081123-75386480-2567-11e9-9a17-8a80af5bb0bd.png)

**Comment by TytanRock** [comment]
So close...
That new line is exactly what you want, but not right there. It goes in
line 9

**Comment by Pharmyy** [comment]
![image](https://user-images.githubusercontent.com/46694778/52081540-774ef300-2568-11e9-9425-8a470fd0ddde.png)
I did that but it had me delete the public PMW1(Servo servo) line

**Comment by TytanRock** [comment]
That is fine. That should compile and do something as long as you change
the max angle to be the actual max angle

**Comment by Pharmyy** [comment]
Should I commit it?

**Comment by TytanRock** [comment]
Go ahead

**Comment by TytanRock** [comment]
This conversation is getting a little out of hand, I'm closing the issue and creating another one for integration and finalization.
