### ISSUE TITLE
Integrate pathfinder into program

### ISSUE THREAD

**Issue by TytanRock** [De-La-Salle-Robotics/Robot-2019#4]
We should integrate the pathfinder formula I committed as an excel file into the program as java code.

This requires:
 - [x] Putting in the math formulas into its own class
 - [x] Creating a localization algorithm to localize the robot with the target
 - [ ] Tuning the robot to follow the path it generates on the fly
 - [ ] Testing on the robot

**Comment by TytanRock** [comment]
We will almost certainly need an IMU on the robot along with encoders on each side of the drive train to gain a reliable sense of control. Will talk to design team to ensure we have the sensors

**Comment by Pharmyy** [comment]
Currently we do not have an IMU or encoders which Petro said you would have to order since it is in your department

**Comment by TytanRock** [comment]
If we want, we can use the vex encoders while I find some other encoders in
the meantime. And I can order the imu from my company and get it next day.
Ask pietro if he can Jerry rig a vex shaft to the drive train and connect
an encoder to it

**Comment by TytanRock** [comment]
https://github.com/De-La-Salle-Robotics/Robot-2019/commit/b603b03f1e3f5f03175617833b5286aff8306f58 adds formulas to the program
